/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ARUSH' at '11/9/16 3:16 PM' with Gradle 2.9
 *
 * @author ARUSH, @date 11/9/16 3:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
